# config for sub-command generate
generate:
  clean: true
  ignoredDataTypes:
    - 'undefined'

# config for sub-command serve
serve:
  port: 8081
  prefixUrl: /mock
  mockOptionalsAlways: true
  mockOptionalsProbability: 0.7
