__globalOptions__:
  encoding: utf-8
  logLevel: verbose
  schemaRootPath: data/schemas
  apiConfigPath:
    - api.yml

# options for sub-command `generate`
generate:
  clean: true
  muteMissingModel: true
  ignoredDataTypes:
    - 'undefined'
  additionalSchemaArgs:
    ref: false
    required: true

# options for sub-command `serve`
serve:
  host: '0.0.0.0'
  port: 8091
  prefixUrl: /mock
  schemaRootPath: data/schema
  mockDataFileFirst: true
  mockDataFileRootPath: data/mock
  mockOptionalsAlways: true
  mockOptionalsProbability: 0.7
